[package]
name = "rhyperx-io"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "I/O and serialization utilities used in the rhyperx hypergraph library."


# [features]
# default = ["serialize"]
# serialize = ["rhyperx-core/serialize"]

[dependencies]
rhyperx-core = { workspace = true, features = ["serialize"] }
rhyperx-algo = { workspace = true }
rhyperx-macros = { workspace = true }

thiserror = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }

toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
