[package]
name = "rhyperx-macros"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Procedural macros used in the rhyperx hypergraph library."

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "visit-mut"] }
quote = "1.0"                                 
proc-macro2 = "1.0"
regex = "1"
