use std::{
    fmt::{Debug, Display},
    ops::{Add, AddAssign},
    time::Duration,
};

pub struct EnumerationStats {
    /// Number of connected and disconnected motifs enumerated
    pub total_count: usize,

    /// Number of connected motifs enumerated
    pub connected_count: usize,

    /// Number of connected motifs enumerated
    pub distinct_fingerprints: usize,

    /// Number of connected motifs enumerated
    pub elapsed_time: Duration,

    /// Number of fingerprints that can be generated by 2 or more motifs that are NOT isomorph.
    /// Should be 0 if the fingerprint invariant used is perfect
    pub clashing_buckets_count: usize,
}

impl EnumerationStats {
    pub fn new() -> Self {
        Self {
            total_count: 0,
            connected_count: 0,
            distinct_fingerprints: 0,
            elapsed_time: Duration::new(0, 0),
            clashing_buckets_count: 0,
        }
    }
}

impl Display for EnumerationStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "Total motifs:          {}\n\
             Connected motifs:      {}\n\
             Distinct fingerprints: {}\n\
             Elapsed time:          {:?}\n\
             Clashing buckets:      {}",
            self.total_count,
            self.connected_count,
            self.distinct_fingerprints,
            self.elapsed_time,
            self.clashing_buckets_count
        )
    }
}

/// A struct containing information about the distribution of a given motif inside a hypergraph
pub struct MotifStats {
    /// Number of distinct motifs subgraphs isomorphic to the given motif
    pub count: usize,

    /// The mean intensity, i.e. the mean intensity between all intances of the motif. Useful
    /// in weighted hypergraphs
    pub mean_intensity: f64,

    /// The mean coherence, i.e. the mean coherence between all intances of the motif. Useful
    /// in weighted hypergraphs
    pub mean_coherence: f64,

    /// The mean actual_intensity, i.e. the mean actual_intensity between all intances of the motif. Useful
    /// in weighted hypergraphs
    pub actual_intensity: f64,
}

impl AddAssign for MotifStats {
    fn add_assign(&mut self, other: Self) {
        self.count += other.count;
        self.mean_intensity += other.mean_intensity;
        self.mean_coherence += other.mean_coherence;
        self.actual_intensity += other.actual_intensity;
    }
}

impl Add for MotifStats {
    type Output = Self;

    fn add(self, other: Self) -> Self::Output {
        Self {
            count: self.count + other.count,
            mean_intensity: self.mean_intensity + other.mean_intensity,
            mean_coherence: self.mean_coherence + other.mean_coherence,
            actual_intensity: self.actual_intensity + other.actual_intensity,
        }
    }
}

impl MotifStats {
    pub fn new() -> Self {
        Self {
            count: 0,
            mean_intensity: 0.0,
            mean_coherence: 1.0,
            actual_intensity: 0.0,
        }
    }
}

impl Display for MotifStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "Count:          {}\n\
             Mean intensity: {}\n\
             Mean coherence: {:?}\n\
             Actual intensity: {}",
            self.count, self.mean_intensity, self.mean_coherence, self.actual_intensity
        )
    }
}

impl Debug for MotifStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "{}", self)
    }
}

pub struct SignificanceProfile {
    pub count: f64,

    pub intensity: f64,

    pub coherence: f64,

    pub actual_intensity: f64,
}

impl SignificanceProfile {
    pub fn new() -> Self {
        Self {
            count: 0.0,
            intensity: 0.0,
            coherence: 0.0,
            actual_intensity: 0.0,
        }
    }
}

impl Display for SignificanceProfile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "Mean count:            {}\n\
             Mean intensity:        {}\n\
             Mean coherence:        {}\n\
             Mean actual intensity: {}",
            self.count, self.intensity, self.coherence, self.actual_intensity
        )
    }
}

impl Debug for SignificanceProfile {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "{}", self)
    }
}

// #[derive(Clone, Copy, PartialEq, Eq)]
// pub enum SPStrategy {
//     ShuffleWeights(),
//     ShuffleEdges(usize),
//     ShuffleBoth(usize),
// }
//
// impl SPStrategy {
//     pub fn apply<W>(&self, adj: &mut HyperAdjList<W>) {
//         match self {
//             SPStrategy::ShuffleWeights() => shuffle_weights(adj),
//             SPStrategy::ShuffleEdges(iterations) => shuffle_edges(adj, *iterations),
//             SPStrategy::ShuffleBoth(iterations) => {
//                 shuffle_weights(adj);
//                 shuffle_edges(adj, *iterations);
//             }
//         }
//     }
// }
//
// impl Display for SPStrategy {
//     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
//         match self {
//             SPStrategy::ShuffleWeights() => write!(f, "ShuffleWeights"),
//             SPStrategy::ShuffleEdges(iterations) => write!(f, "ShuffleEdges({})", iterations),
//             SPStrategy::ShuffleBoth(iterations) => write!(f, "ShuffleBoth({})", iterations),
//         }
//     }
// }
//
// impl Debug for SPStrategy {
//     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
//         writeln!(f, "{}", self)
//     }
// }
