[package]
name = "rhyperx-core"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Core functionalities and data structures of the rhyperx hypergraph library."

[dependencies]
thiserror = { workspace = true }
foldhash = { workspace = true }
hashbrown = { workspace = true }
num-traits = { workspace = true }
rkyv = { workspace = true }
