[package]
name = "rhyperx-core"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Core functionalities and data structures of the rhyperx hypergraph library."

[features]
default = []
serialize = ["dep:rkyv", "dep:ouroboros"]

[dependencies]
rhyperx-macros = { workspace = true }

duplicate = { workspace = true }
thiserror = { workspace = true }
foldhash = { workspace = true }
hashbrown = { workspace = true }
rkyv = { workspace = true, optional = true }
ouroboros = { workspace = true, optional = true }
