[package]
name = "rhyperx-algo"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "All non-trivial algorithms implemented in the rhyperx hypergraph library."

[dependencies]
rhyperx-macros = { workspace = true }
rhyperx-core = { workspace = true }

duplicate = { workspace = true }
foldhash = { workspace = true }
hashbrown = { workspace = true }
num-traits = { workspace = true }
paste = { workspace = true }
thiserror = { workspace = true }
rkyv = { workspace = true }


bitvec = "1.1.1"
