[package]
name = "rhyperx"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Graph and hypergraph data structures and algorithms library"

[lib]
crate-type = ["rlib"]

[features]
default = ["algo"]
algo = ["dep:rhyperx-algo"]
io = ["dep:rhyperx-io"]
serialize = ["rhyperx-core/serialize"]

[dependencies]
rhyperx-core = { workspace = true }
rhyperx-algo = { workspace = true, optional = true }
rhyperx-io = { workspace = true, optional = true }
