[package]
name = "rhyperx"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Graph and hypergraph data structures and algorithms library"

[lib]
crate-type = ["rlib"]

[dependencies]
rhyperx-macros = { workspace = true }

bit-set = { workspace = true }
num-traits = { workspace = true }
seq-macro = { workspace = true }
rand = { workspace = true }
env_logger = { workspace = true }

rkyv = { version = "0.8.15", features = ["hashbrown-0_17"] }
ouroboros = { version = "0.18.5" }
indicatif = { workspace = true }
csv = { version = "1.2" }
timed = { version = "0.2.1" }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.8" }

log = { workspace = true }


hashbrown = { workspace = true }
foldhash = { workspace = true }
paste = { workspace = true }
anyhow = { workspace = true }
